### ISSUE TITLE
This is completely broken now from the new gmod update have any ideas on how to fix it ?

### ISSUE THREAD

**Issue by Smartjer123** [cobalt77/Screengrab#5]
render.Capture changes
Before this update render.Capture could be used by addons to view third-party overlays, such as Steam or Discord. This is no longer the case, as render.Capture will now only return pixels that have been rendered in the current frame.

This will not affect addons that are drawing something to the screen and then using render.Capture to get what has been drawn as image data, but may affect addons that are attempting to take screenshots of the game. If you are writing an addon that is trying to take screenshots, you should be calling render.Capture in the PostRender hook.

**Comment by CubXD** [comment]
The read me for the addon says he doesnt have the time to support it so idk if this will get an answer. I'm talking with my dev on how to fix it. Apparently it's like a 1 line fix

**Comment by Smartjer123** [comment]
Ok, this is the only thing that can see those cheats that are undetected like Big Packets. If you normally spectate them they could see that you are spectating them

**Comment by Smartjer123** [comment]
Gmod said that render.capture now needs to be called with a hook in there new update and screengrab uses render.capture: 

render.Capture changes
Before this update render.Capture could be used by addons to view third-party overlays, such as Steam or Discord. This is no longer the case, as render.Capture will now only return pixels that have been rendered in the current frame.

This will not affect addons that are drawing something to the screen and then using render.Capture to get what has been drawn as image data, but may affect addons that are attempting to take screenshots of the game. If you are writing an addon that is trying to take screenshots, you should be calling render.Capture in the PostRender hook.

**Comment by Smartjer123** [comment]
Even if you do get it working you might not be able to see the cheats

**Comment by Smartjer123** [comment]
This really sucks for me because I run a sandbox server and I use this to catch the big packets cheaters. I am the owner of Smarter Sandbox btw

**Comment by Smartjer123** [comment]
I got CAC when it detected 100% of cheaters now it detects about 50-70% because of those undetected cheats. It also sucks how !cake is not really taking any action. I asked him about it and he  said was "ok" and that was in 2017

**Comment by CubXD** [comment]
There is a screengrab on GMS that is being actively supported and also supports screen livestreaming. Never personally tried it but it is an alternative and I think there's 1 or 2 more things it can detect.

**Comment by cobalt77** [comment]
Like CubXD says, I no longer have time to support this and will not update the code. However, if you find someone who would be willing to, feel free to submit a pull request and I will be happy to merge in the changes.

**Comment by KittoniuM** [comment]
Very good, I will use this to make defeat the evil entities "Big Packets", pesky cheaters with a lot of bag in brain, We are stronger than stupid pesky cheater with a wood (bark) in brain of cheater.
