### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by jamesjasl** [cobalt77/Screengrab#7]
Hey, I uploaded the **folder** "screengrab-master" to the lua >> autorun folder. but it doesn't work on my server. Do I upload the zip or actual file?

**Comment by LucasStonePERPNET** [comment]
Jesus Christ. Are you for real? You need to place the folder inside of your addons folder and get rid of the '-master' part the folder name.

**Comment by cobalt77** [comment]
You only have to put the .lua file inside lua/autorun, not the whole folder.
